default_language_version:
  python: python3.10

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files



-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort


-   repo: https://github.com/thibaudcolas/curlylint
    rev: v0.13.1
    hooks:
    -   id: curlylint



-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
    -   id: prettier
        types_or:
        -   css
        -   xml
        additional_dependencies:
        -   prettier@2.5.1
        -   '@prettier/plugin-xml@1.2.0'
